### ISSUE TITLE
API Version hard-coded

### ISSUE THREAD

**Issue by Chamane** [certilremy/moncash_ruby#3]
API version is hard-coded. It must be flexible to edit and to adjust as other configuration. This must be fixed because the API number provided by MonCash for any reason can change for improvements and update

**Comment by certilremy** [comment]
> API version is hard-coded. It must be flexible to edit and to adjust as other configurations. This must be fixed because the API number provided by MonCash for any reason can change for improvements and update

Thank you, Madsen, for the issue, however, this is a wrapper to help the ruby developers make requests to moncash, it's not responsible for versioning. If you feel the needs of this feature you can open a pull request with it, we will review and merge it as soon as possible.
